In [1]:

# Core / Dados
!pip install pandas numpy

# NLP - spaCy
!pip install spacy
!python -m spacy download en_core_web_sm

# NLP - NLTK
!pip install nltk

# NLP - Stanza
!pip install stanza

# Machine Learning
!pip install scikit-learn

# Sentiment Analysis
!pip install textblob
!pip install vaderSentiment

# Deep Learning / Transformers
!pip install torch
!pip install transformers
!pip install accelerate

# Visualização
!pip install matplotlib

# Requests (para API externa)
!pip install requests

Requirement already satisfied: pandas in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting spacy
  Downloading spacy-3.8.14-cp312-cp312-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Using cached spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.13-cp312-cp312-win_amd64.whl.metadata (5.4 kB)
Collecting thinc<8.4.0,>=8.3.12 (from spacy)
  Downloading thinc-8.3.13-cp312-cp312-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Using cached wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.5.3 (from spacy)
  Downloading srsly-2.5.3-cp312-cp312-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Using cached catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<2.0.0,>=1.0.0 (from spacy)
  Using cached weasel-1.0.0-py3-none-any.whl.metadata (4.6 kB)
Collecting confection<2.0.0,>=1.3.2 (from spacy)
  Using cached confection-1.3.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from spacy) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from spacy) (2.0.0)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from spacy) (2.32.5)
Collecting pydantic<3.0.0,>=2.0.0 (from spacy)
  Downloading pydantic-2.13.3-py3-none-any.whl.metadata (108 kB)
Collecting jinja2 (from spacy)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: setuptools in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from spacy) (80.3.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anton\appdata\roaming\python\python312\site-packages (from spacy) (24.2)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.3 (from pydantic<3.0.0,>=2.0.0->spacy)
  Downloading pydantic_core-2.46.3-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->spacy)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.12->spacy)
  Downloading blis-1.3.3-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: colorama in c:\users\anton\appdata\roaming\python\python312\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Collecting cloudpathlib>=0.7.0 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open>=5.2.1 (from weasel<2.0.0,>=1.0.0->spacy)
  Using cached smart_open-7.6.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: httpx>=0.24.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.12.1)
Requirement already satisfied: httpcore==1.* in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\anton\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting wrapt (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy)
  Downloading wrapt-2.1.2-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->spacy)
  Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Downloading spacy-3.8.14-cp312-cp312-win_amd64.whl (14.2 MB)
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
    --------------------------------------- 0.3/14.2 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.2 MB 1.3 MB/s eta 0:00:11
   -- ------------------------------------- 0.8/14.2 MB 1.5 MB/s eta 0:00:09
   --- ------------------------------------ 1.3/14.2 MB 1.8 MB/s eta 0:00:08
   ----- ---------------------------------- 1.8/14.2 MB 1.9 MB/s eta 0:00:07
   ------- -------------------------------- 2.6/14.2 MB 2.2 MB/s eta 0:00:06
   --------- ------------------------------ 3.4/14.2 MB 2.5 MB/s eta 0:00:05
   ----------- ---------------------------- 4.2/14.2 MB 2.6 MB/s eta 0:00:04
   -------------- ------------------------- 5.0/14.2 MB 2.7 MB/s eta 0:00:04
   ---------------- ----------------------- 5.8/14.2 MB 2.8 MB/s eta 0:00:04
   ------------------ --------------------- 6.6/14.2 MB 2.9 MB/s eta 0:00:03
   ------------------- -------------------- 7.1/14.2 MB 2.9 MB/s eta 0:00:03
   -------------------- ------------------- 7.3/14.2 MB 2.8 MB/s eta 0:00:03
   --------------------- ------------------ 7.6/14.2 MB 2.8 MB/s eta 0:00:03
   ---------------------- ----------------- 7.9/14.2 MB 2.6 MB/s eta 0:00:03
   ------------------------ --------------- 8.7/14.2 MB 2.6 MB/s eta 0:00:03
   ------------------------- -------------- 9.2/14.2 MB 2.6 MB/s eta 0:00:02
   ---------------------------- ----------- 10.0/14.2 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 10.7/14.2 MB 2.7 MB/s eta 0:00:02
   ------------------------------- -------- 11.3/14.2 MB 2.7 MB/s eta 0:00:02
   --------------------------------- ------ 12.1/14.2 MB 2.8 MB/s eta 0:00:01
   ------------------------------------ --- 12.8/14.2 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 13.4/14.2 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  14.2/14.2 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 14.2/14.2 MB 2.8 MB/s eta 0:00:00
Using cached catalogue-2.0.10-py3-none-any.whl (17 kB)
Using cached confection-1.3.3-py3-none-any.whl (35 kB)
Downloading cymem-2.0.13-cp312-cp312-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp312-cp312-win_amd64.whl (25 kB)
Downloading preshed-3.0.13-cp312-cp312-win_amd64.whl (122 kB)
Downloading pydantic-2.13.3-py3-none-any.whl (471 kB)
Downloading pydantic_core-2.46.3-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.1 MB 3.4 MB/s eta 0:00:01
   ------------------------- -------------- 1.3/2.1 MB 3.2 MB/s eta 0:00:01
   ----------------------------------- ---- 1.8/2.1 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 2.8 MB/s eta 0:00:00
Using cached spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Using cached spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.3-cp312-cp312-win_amd64.whl (652 kB)
   ---------------------------------------- 0.0/652.5 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/652.5 kB ? eta -:--:--
   ---------------------------------------- 652.5/652.5 kB 3.6 MB/s eta 0:00:00
Downloading thinc-8.3.13-cp312-cp312-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 4.2 MB/s eta 0:00:01
   ------------------------------ --------- 1.3/1.7 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 3.7 MB/s eta 0:00:00
Downloading blis-1.3.3-cp312-cp312-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.2 MB 3.4 MB/s eta 0:00:02
   -------- ------------------------------- 1.3/6.2 MB 3.4 MB/s eta 0:00:02
   ------------- -------------------------- 2.1/6.2 MB 3.4 MB/s eta 0:00:02
   ---------------- ----------------------- 2.6/6.2 MB 3.3 MB/s eta 0:00:02
   -------------------- ------------------- 3.1/6.2 MB 3.1 MB/s eta 0:00:01
   -------------------- ------------------- 3.1/6.2 MB 3.1 MB/s eta 0:00:01
   ------------------------- -------------- 3.9/6.2 MB 2.6 MB/s eta 0:00:01
   --------------------------- ------------ 4.2/6.2 MB 2.6 MB/s eta 0:00:01
   ------------------------------ --------- 4.7/6.2 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 5.2/6.2 MB 2.5 MB/s eta 0:00:01
   ----------------------------------- ---- 5.5/6.2 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 6.0/6.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 2.3 MB/s eta 0:00:00
Using cached wasabi-1.1.3-py3-none-any.whl (27 kB)
Using cached weasel-1.0.0-py3-none-any.whl (50 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Using cached smart_open-7.6.0-py3-none-any.whl (64 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp312-cp312-win_amd64.whl (15 kB)
Downloading wrapt-2.1.2-cp312-cp312-win_amd64.whl (60 kB)
Installing collected packages: wrapt, wasabi, typing-inspection, spacy-loggers, spacy-legacy, pydantic-core, murmurhash, MarkupSafe, cymem, confection, cloudpathlib, catalogue, blis, annotated-types, srsly, smart-open, pydantic, preshed, jinja2, thinc, weasel, spacy

   ----------------------------------------  0/22 [wrapt]
   - --------------------------------------  1/22 [wasabi]
   - --------------------------------------  1/22 [wasabi]
   ----- ----------------------------------  3/22 [spacy-loggers]
   ----- ----------------------------------  3/22 [spacy-loggers]
   ------- --------------------------------  4/22 [spacy-legacy]
   --------- ------------------------------  5/22 [pydantic-core]
   ---------- -----------------------------  6/22 [murmurhash]
   ---------------- -----------------------  9/22 [confection]
   ---------------- -----------------------  9/22 [confection]
   ------------------ --------------------- 10/22 [cloudpathlib]
   ------------------ --------------------- 10/22 [cloudpathlib]
   ------------------ --------------------- 10/22 [cloudpathlib]
   -------------------- ------------------- 11/22 [catalogue]
   --------------------- ------------------ 12/22 [blis]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   ------------------------- -------------- 14/22 [srsly]
   --------------------------- ------------ 15/22 [smart-open]
   --------------------------- ------------ 15/22 [smart-open]
   --------------------------- ------------ 15/22 [smart-open]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   ----------------------------- ---------- 16/22 [pydantic]
   -------------------------------- ------- 18/22 [jinja2]
   -------------------------------- ------- 18/22 [jinja2]
   -------------------------------- ------- 18/22 [jinja2]
   -------------------------------- ------- 18/22 [jinja2]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ---------------------------------- ----- 19/22 [thinc]
   ------------------------------------ --- 20/22 [weasel]
   ------------------------------------ --- 20/22 [weasel]
   ------------------------------------ --- 20/22 [weasel]
   ------------------------------------ --- 20/22 [weasel]
   ------------------------------------ --- 20/22 [weasel]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]
   -------------------------------------- - 21/22 [spacy]

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.8 MB 2.4 MB/s eta 0:00:06
     -- ------------------------------------- 0.8/12.8 MB 1.7 MB/s eta 0:00:08
     ---- ----------------------------------- 1.3/12.8 MB 1.8 MB/s eta 0:00:07
     ----- ---------------------------------- 1.8/12.8 MB 2.1 MB/s eta 0:00:06
     ------- -------------------------------- 2.4/12.8 MB 2.2 MB/s eta 0:00:05
     -------- ------------------------------- 2.6/12.8 MB 2.1 MB/s eta 0:00:05
     --------- ------------------------------ 2.9/12.8 MB 2.1 MB/s eta 0:00:05
     --------- ------------------------------ 3.1/12.8 MB 1.9 MB/s eta 0:00:06
     ---------- ----------------------------- 3.4/12.8 MB 1.8 MB/s eta 0:00:06
     ------------ --------------------------- 3.9/12.8 MB 1.8 MB/s eta 0:00:05
     ------------- -------------------------- 4.5/12.8 MB 1.8 MB/s eta 0:00:05
     -------------- ------------------------- 4.7/12.8 MB 1.8 MB/s eta 0:00:05
     ---------------- ----------------------- 5.2/12.8 MB 1.9 MB/s eta 0:00:05
     ------------------ --------------------- 5.8/12.8 MB 1.9 MB/s eta 0:00:04
     ------------------- -------------------- 6.3/12.8 MB 2.0 MB/s eta 0:00:04
     ---------------------- ----------------- 7.1/12.8 MB 2.0 MB/s eta 0:00:03
     ----------------------- ---------------- 7.6/12.8 MB 2.1 MB/s eta 0:00:03
     ------------------------- -------------- 8.1/12.8 MB 2.1 MB/s eta 0:00:03
     --------------------------- ------------ 8.7/12.8 MB 2.2 MB/s eta 0:00:02
     ---------------------------- ----------- 9.2/12.8 MB 2.2 MB/s eta 0:00:02
     ------------------------------ --------- 9.7/12.8 MB 2.1 MB/s eta 0:00:02
     ------------------------------- -------- 10.0/12.8 MB 2.1 MB/s eta 0:00:02
     -------------------------------- ------- 10.5/12.8 MB 2.1 MB/s eta 0:00:02
     ---------------------------------- ----- 11.0/12.8 MB 2.1 MB/s eta 0:00:01
     ---------------------------------- ----- 11.0/12.8 MB 2.1 MB/s eta 0:00:01
     ---------------------------------- ----- 11.0/12.8 MB 2.1 MB/s eta 0:00:01
     ------------------------------------ --- 11.5/12.8 MB 2.0 MB/s eta 0:00:01
     ------------------------------------ --- 11.8/12.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 1.9 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting nltk
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Using cached regex-2026.4.4-cp312-cp312-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: tqdm in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in c:\users\anton\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)
Using cached nltk-3.9.4-py3-none-any.whl (1.6 MB)
Downloading regex-2026.4.4-cp312-cp312-win_amd64.whl (277 kB)
Installing collected packages: regex, nltk

   ---------------------------------------- 0/2 [regex]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   -------------------- ------------------- 1/2 [nltk]
   ---------------------------------------- 2/2 [nltk]

Successfully installed nltk-3.9.4 regex-2026.4.4

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting stanza
  Using cached stanza-1.11.1-py3-none-any.whl.metadata (14 kB)
Collecting emoji (from stanza)
  Using cached emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: numpy in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from stanza) (2.0.0)
Requirement already satisfied: platformdirs in c:\users\anton\appdata\roaming\python\python312\site-packages (from stanza) (4.3.7)
Collecting protobuf>=3.15.0 (from stanza)
  Using cached protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from stanza) (2.32.5)
Collecting networkx (from stanza)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting torch>=1.13.0 (from stanza)
  Using cached torch-2.11.0-cp312-cp312-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: tqdm in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from stanza) (4.67.3)
Collecting udtools>=0.2.4 (from stanza)
  Using cached udtools-0.2.7-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.13.0->stanza) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.13.0->stanza) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.13.0->stanza) (80.3.0)
Collecting sympy>=1.13.3 (from torch>=1.13.0->stanza)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: jinja2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.13.0->stanza) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.13.0->stanza) (2026.2.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.13.0->stanza)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting udapi>=0.5.0 (from udtools>=0.2.4->stanza)
  Using cached udapi-0.5.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: regex>=2020.09.27 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from udtools>=0.2.4->stanza) (2026.4.4)
Requirement already satisfied: colorama in c:\users\anton\appdata\roaming\python\python312\site-packages (from udapi>=0.5.0->udtools>=0.2.4->stanza) (0.4.6)
Collecting termcolor (from udapi>=0.5.0->udtools>=0.2.4->stanza)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=1.13.0->stanza) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests->stanza) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests->stanza) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests->stanza) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests->stanza) (2026.2.25)
Using cached stanza-1.11.1-py3-none-any.whl (1.7 MB)
Using cached protobuf-7.34.1-cp310-abi3-win_amd64.whl (437 kB)
Downloading torch-2.11.0-cp312-cp312-win_amd64.whl (114.6 MB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/114.6 MB ? eta -:--:--
   ---------------------------------------- 0.5/114.6 MB 1.2 MB/s eta 0:01:36
   ---------------------------------------- 0.8/114.6 MB 1.1 MB/s eta 0:01:42
   ---------------------------------------- 1.0/114.6 MB 1.1 MB/s eta 0:01:42
   ---------------------------------------- 1.3/114.6 MB 1.2 MB/s eta 0:01:38
    --------------------------------------- 1.6/114.6 MB 1.2 MB/s eta 0:01:33
    --------------------------------------- 2.1/114.6 MB 1.4 MB/s eta 0:01:23
    --------------------------------------- 2.6/114.6 MB 1.6 MB/s eta 0:01:12
   - -------------------------------------- 3.1/114.6 MB 1.6 MB/s eta 0:01:09
   - -------------------------------------- 3.9/114.6 MB 1.9 MB/s eta 0:01:00
   - -------------------------------------- 4.7/114.6 MB 2.0 MB/s eta 0:00:55
   - -------------------------------------- 5.0/114.6 MB 2.0 MB/s eta 0:00:55
   - -------------------------------------- 5.2/114.6 MB 2.0 MB/s eta 0:00:56
   - -------------------------------------- 5.2/114.6 MB 2.0 MB/s eta 0:00:56
   - -------------------------------------- 5.5/114.6 MB 1.8 MB/s eta 0:01:03
   - -------------------------------------- 5.5/114.6 MB 1.8 MB/s eta 0:01:03
   -- ------------------------------------- 5.8/114.6 MB 1.6 MB/s eta 0:01:10
   -- ------------------------------------- 5.8/114.6 MB 1.6 MB/s eta 0:01:10
   -- ------------------------------------- 6.0/114.6 MB 1.5 MB/s eta 0:01:12
   -- ------------------------------------- 6.0/114.6 MB 1.5 MB/s eta 0:01:12
   -- ------------------------------------- 6.3/114.6 MB 1.4 MB/s eta 0:01:17
   -- ------------------------------------- 6.3/114.6 MB 1.4 MB/s eta 0:01:17
   -- ------------------------------------- 6.6/114.6 MB 1.4 MB/s eta 0:01:20
   -- ------------------------------------- 6.8/114.6 MB 1.3 MB/s eta 0:01:22
   -- ------------------------------------- 7.1/114.6 MB 1.3 MB/s eta 0:01:23
   -- ------------------------------------- 7.3/114.6 MB 1.3 MB/s eta 0:01:22
   -- ------------------------------------- 7.6/114.6 MB 1.3 MB/s eta 0:01:21
   -- ------------------------------------- 7.9/114.6 MB 1.3 MB/s eta 0:01:21
   -- ------------------------------------- 8.4/114.6 MB 1.4 MB/s eta 0:01:19
   --- ------------------------------------ 8.7/114.6 MB 1.4 MB/s eta 0:01:19
   --- ------------------------------------ 8.9/114.6 MB 1.4 MB/s eta 0:01:18
   --- ------------------------------------ 9.4/114.6 MB 1.4 MB/s eta 0:01:17
   --- ------------------------------------ 9.7/114.6 MB 1.4 MB/s eta 0:01:16
   --- ------------------------------------ 9.7/114.6 MB 1.4 MB/s eta 0:01:16
   --- ------------------------------------ 10.2/114.6 MB 1.4 MB/s eta 0:01:17
   --- ------------------------------------ 10.5/114.6 MB 1.4 MB/s eta 0:01:17
   --- ------------------------------------ 10.7/114.6 MB 1.4 MB/s eta 0:01:17
   --- ------------------------------------ 11.0/114.6 MB 1.4 MB/s eta 0:01:17
   ---- ----------------------------------- 11.5/114.6 MB 1.4 MB/s eta 0:01:15
   ---- ----------------------------------- 12.1/114.6 MB 1.4 MB/s eta 0:01:13
   ---- ----------------------------------- 12.6/114.6 MB 1.4 MB/s eta 0:01:12
   ---- ----------------------------------- 12.8/114.6 MB 1.4 MB/s eta 0:01:11
   ---- ----------------------------------- 13.1/114.6 MB 1.4 MB/s eta 0:01:11
   ---- ----------------------------------- 13.4/114.6 MB 1.4 MB/s eta 0:01:11
   ---- ----------------------------------- 13.9/114.6 MB 1.4 MB/s eta 0:01:10
   ---- ----------------------------------- 14.2/114.6 MB 1.4 MB/s eta 0:01:10
   ----- ---------------------------------- 14.4/114.6 MB 1.4 MB/s eta 0:01:10
   ----- ---------------------------------- 14.7/114.6 MB 1.4 MB/s eta 0:01:10
   ----- ---------------------------------- 14.9/114.6 MB 1.4 MB/s eta 0:01:10
   ----- ---------------------------------- 15.2/114.6 MB 1.4 MB/s eta 0:01:10
   ----- ---------------------------------- 15.2/114.6 MB 1.4 MB/s eta 0:01:10
   ----- ---------------------------------- 15.2/114.6 MB 1.4 MB/s eta 0:01:10
   ----- ---------------------------------- 15.5/114.6 MB 1.4 MB/s eta 0:01:13
   ----- ---------------------------------- 16.0/114.6 MB 1.4 MB/s eta 0:01:11
   ----- ---------------------------------- 16.0/114.6 MB 1.4 MB/s eta 0:01:11
   ----- ---------------------------------- 16.0/114.6 MB 1.4 MB/s eta 0:01:11
   ----- ---------------------------------- 16.3/114.6 MB 1.3 MB/s eta 0:01:14
   ----- ---------------------------------- 16.5/114.6 MB 1.3 MB/s eta 0:01:14
   ----- ---------------------------------- 16.5/114.6 MB 1.3 MB/s eta 0:01:14
   ----- ---------------------------------- 16.8/114.6 MB 1.3 MB/s eta 0:01:15
   ----- ---------------------------------- 16.8/114.6 MB 1.3 MB/s eta 0:01:15
   ----- ---------------------------------- 16.8/114.6 MB 1.3 MB/s eta 0:01:15
   ----- ---------------------------------- 17.0/114.6 MB 1.3 MB/s eta 0:01:17
   ----- ---------------------------------- 17.0/114.6 MB 1.3 MB/s eta 0:01:17
   ------ --------------------------------- 17.3/114.6 MB 1.2 MB/s eta 0:01:18
   ------ --------------------------------- 17.6/114.6 MB 1.2 MB/s eta 0:01:19
   ------ --------------------------------- 17.8/114.6 MB 1.2 MB/s eta 0:01:18
   ------ --------------------------------- 18.4/114.6 MB 1.3 MB/s eta 0:01:17
   ------ --------------------------------- 18.6/114.6 MB 1.3 MB/s eta 0:01:16
   ------ --------------------------------- 18.9/114.6 MB 1.3 MB/s eta 0:01:16
   ------ --------------------------------- 19.4/114.6 MB 1.3 MB/s eta 0:01:15
   ------ --------------------------------- 19.9/114.6 MB 1.3 MB/s eta 0:01:13
   ------- -------------------------------- 20.4/114.6 MB 1.3 MB/s eta 0:01:12
   ------- -------------------------------- 21.0/114.6 MB 1.3 MB/s eta 0:01:11
   ------- -------------------------------- 21.5/114.6 MB 1.3 MB/s eta 0:01:10
   ------- -------------------------------- 22.0/114.6 MB 1.4 MB/s eta 0:01:09
   ------- -------------------------------- 22.5/114.6 MB 1.4 MB/s eta 0:01:07
   -------- ------------------------------- 23.1/114.6 MB 1.4 MB/s eta 0:01:06
   -------- ------------------------------- 23.6/114.6 MB 1.4 MB/s eta 0:01:05
   -------- ------------------------------- 24.1/114.6 MB 1.4 MB/s eta 0:01:04
   -------- ------------------------------- 24.6/114.6 MB 1.4 MB/s eta 0:01:03
   -------- ------------------------------- 25.4/114.6 MB 1.5 MB/s eta 0:01:02
   -------- ------------------------------- 25.7/114.6 MB 1.5 MB/s eta 0:01:01
   --------- ------------------------------ 26.2/114.6 MB 1.5 MB/s eta 0:01:01
   --------- ------------------------------ 26.7/114.6 MB 1.5 MB/s eta 0:01:00
   --------- ------------------------------ 27.3/114.6 MB 1.5 MB/s eta 0:00:59
   --------- ------------------------------ 27.8/114.6 MB 1.5 MB/s eta 0:00:58
   --------- ------------------------------ 28.3/114.6 MB 1.5 MB/s eta 0:00:58
   ---------- ----------------------------- 28.8/114.6 MB 1.5 MB/s eta 0:00:57
   ---------- ----------------------------- 29.6/114.6 MB 1.5 MB/s eta 0:00:55
   ---------- ----------------------------- 30.1/114.6 MB 1.6 MB/s eta 0:00:55
   ---------- ----------------------------- 30.7/114.6 MB 1.6 MB/s eta 0:00:54
   ---------- ----------------------------- 31.2/114.6 MB 1.6 MB/s eta 0:00:53
   ----------- ---------------------------- 31.7/114.6 MB 1.6 MB/s eta 0:00:53
   ----------- ---------------------------- 32.2/114.6 MB 1.6 MB/s eta 0:00:52
   ----------- ---------------------------- 32.8/114.6 MB 1.6 MB/s eta 0:00:51
   ----------- ---------------------------- 33.6/114.6 MB 1.6 MB/s eta 0:00:50
   ----------- ---------------------------- 34.3/114.6 MB 1.6 MB/s eta 0:00:49
   ------------ --------------------------- 35.1/114.6 MB 1.7 MB/s eta 0:00:48
   ------------ --------------------------- 35.7/114.6 MB 1.7 MB/s eta 0:00:47
   ------------ --------------------------- 36.4/114.6 MB 1.7 MB/s eta 0:00:46
   ------------ --------------------------- 37.2/114.6 MB 1.7 MB/s eta 0:00:46
   ------------- -------------------------- 38.0/114.6 MB 1.7 MB/s eta 0:00:45
   ------------- -------------------------- 38.8/114.6 MB 1.8 MB/s eta 0:00:44
   ------------- -------------------------- 39.3/114.6 MB 1.8 MB/s eta 0:00:43
   ------------- -------------------------- 39.6/114.6 MB 1.8 MB/s eta 0:00:43
   ------------- -------------------------- 39.8/114.6 MB 1.8 MB/s eta 0:00:43
   ------------- -------------------------- 39.8/114.6 MB 1.8 MB/s eta 0:00:43
   -------------- ------------------------- 40.4/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 40.6/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 40.6/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 40.9/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 41.2/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 41.4/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 41.7/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 41.9/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 42.5/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 42.5/114.6 MB 1.7 MB/s eta 0:00:43
   -------------- ------------------------- 42.7/114.6 MB 1.7 MB/s eta 0:00:43
   --------------- ------------------------ 43.3/114.6 MB 1.7 MB/s eta 0:00:43
   --------------- ------------------------ 44.0/114.6 MB 1.7 MB/s eta 0:00:42
   --------------- ------------------------ 44.6/114.6 MB 1.7 MB/s eta 0:00:41
   --------------- ------------------------ 45.1/114.6 MB 1.7 MB/s eta 0:00:41
   --------------- ------------------------ 45.1/114.6 MB 1.7 MB/s eta 0:00:41
   --------------- ------------------------ 45.4/114.6 MB 1.7 MB/s eta 0:00:41
   ---------------- ----------------------- 45.9/114.6 MB 1.7 MB/s eta 0:00:41
   ---------------- ----------------------- 46.1/114.6 MB 1.7 MB/s eta 0:00:40
   ---------------- ----------------------- 46.7/114.6 MB 1.7 MB/s eta 0:00:40
   ---------------- ----------------------- 47.4/114.6 MB 1.7 MB/s eta 0:00:39
   ---------------- ----------------------- 48.0/114.6 MB 1.7 MB/s eta 0:00:39
   ---------------- ----------------------- 48.5/114.6 MB 1.7 MB/s eta 0:00:38
   ----------------- ---------------------- 49.0/114.6 MB 1.7 MB/s eta 0:00:38
   ----------------- ---------------------- 49.5/114.6 MB 1.7 MB/s eta 0:00:38
   ----------------- ---------------------- 50.1/114.6 MB 1.8 MB/s eta 0:00:37
   ----------------- ---------------------- 50.9/114.6 MB 1.8 MB/s eta 0:00:36
   ------------------ --------------------- 51.6/114.6 MB 1.8 MB/s eta 0:00:36
   ------------------ --------------------- 52.4/114.6 MB 1.8 MB/s eta 0:00:35
   ------------------ --------------------- 53.0/114.6 MB 1.8 MB/s eta 0:00:35
   ------------------ --------------------- 53.7/114.6 MB 1.8 MB/s eta 0:00:34
   ------------------- -------------------- 54.5/114.6 MB 1.8 MB/s eta 0:00:33
   ------------------- -------------------- 55.1/114.6 MB 1.8 MB/s eta 0:00:33
   ------------------- -------------------- 55.3/114.6 MB 1.8 MB/s eta 0:00:33
   ------------------- -------------------- 55.8/114.6 MB 1.8 MB/s eta 0:00:32
   ------------------- -------------------- 56.6/114.6 MB 1.9 MB/s eta 0:00:32
   -------------------- ------------------- 57.4/114.6 MB 1.9 MB/s eta 0:00:31
   -------------------- ------------------- 58.2/114.6 MB 1.9 MB/s eta 0:00:30
   -------------------- ------------------- 58.7/114.6 MB 1.9 MB/s eta 0:00:30
   -------------------- ------------------- 59.5/114.6 MB 1.9 MB/s eta 0:00:29
   -------------------- ------------------- 60.0/114.6 MB 1.9 MB/s eta 0:00:29
   --------------------- ------------------ 60.6/114.6 MB 1.9 MB/s eta 0:00:29
   --------------------- ------------------ 61.1/114.6 MB 1.9 MB/s eta 0:00:29
   --------------------- ------------------ 61.9/114.6 MB 1.9 MB/s eta 0:00:28
   --------------------- ------------------ 62.7/114.6 MB 1.9 MB/s eta 0:00:28
   ---------------------- ----------------- 63.2/114.6 MB 1.9 MB/s eta 0:00:27
   ---------------------- ----------------- 64.0/114.6 MB 2.0 MB/s eta 0:00:26
   ---------------------- ----------------- 64.7/114.6 MB 2.0 MB/s eta 0:00:25
   ---------------------- ----------------- 65.3/114.6 MB 2.0 MB/s eta 0:00:25
   ---------------------- ----------------- 65.5/114.6 MB 2.0 MB/s eta 0:00:25
   ---------------------- ----------------- 65.8/114.6 MB 2.0 MB/s eta 0:00:25
   ---------------------- ----------------- 65.8/114.6 MB 2.0 MB/s eta 0:00:25
   ----------------------- ---------------- 66.1/114.6 MB 2.0 MB/s eta 0:00:25
   ----------------------- ---------------- 66.3/114.6 MB 2.0 MB/s eta 0:00:24
   ----------------------- ---------------- 66.6/114.6 MB 2.0 MB/s eta 0:00:24
   ----------------------- ---------------- 66.8/114.6 MB 2.0 MB/s eta 0:00:24
   ----------------------- ---------------- 67.1/114.6 MB 2.0 MB/s eta 0:00:24
   ----------------------- ---------------- 67.6/114.6 MB 2.0 MB/s eta 0:00:24
   ----------------------- ---------------- 68.2/114.6 MB 2.0 MB/s eta 0:00:23
   ----------------------- ---------------- 68.4/114.6 MB 2.0 MB/s eta 0:00:23
   ------------------------ --------------- 68.9/114.6 MB 2.0 MB/s eta 0:00:23
   ------------------------ --------------- 69.5/114.6 MB 2.0 MB/s eta 0:00:23
   ------------------------ --------------- 70.3/114.6 MB 2.1 MB/s eta 0:00:22
   ------------------------ --------------- 71.0/114.6 MB 2.1 MB/s eta 0:00:22
   ------------------------- -------------- 71.8/114.6 MB 2.1 MB/s eta 0:00:21
   ------------------------- -------------- 72.6/114.6 MB 2.1 MB/s eta 0:00:20
   ------------------------- -------------- 73.1/114.6 MB 2.1 MB/s eta 0:00:20
   ------------------------- -------------- 73.9/114.6 MB 2.1 MB/s eta 0:00:20
   ------------------------- -------------- 74.4/114.6 MB 2.1 MB/s eta 0:00:19
   -------------------------- ------------- 74.7/114.6 MB 2.1 MB/s eta 0:00:19
   -------------------------- ------------- 75.2/114.6 MB 2.1 MB/s eta 0:00:19
   -------------------------- ------------- 75.8/114.6 MB 2.1 MB/s eta 0:00:19
   -------------------------- ------------- 76.5/114.6 MB 2.1 MB/s eta 0:00:18
   --------------------------- ------------ 77.3/114.6 MB 2.2 MB/s eta 0:00:18
   --------------------------- ------------ 78.1/114.6 MB 2.2 MB/s eta 0:00:17
   --------------------------- ------------ 78.9/114.6 MB 2.2 MB/s eta 0:00:17
   --------------------------- ------------ 79.4/114.6 MB 2.2 MB/s eta 0:00:16
   ---------------------------- ----------- 80.2/114.6 MB 2.2 MB/s eta 0:00:16
   ---------------------------- ----------- 81.0/114.6 MB 2.2 MB/s eta 0:00:16
   ---------------------------- ----------- 81.8/114.6 MB 2.2 MB/s eta 0:00:15
   ---------------------------- ----------- 82.6/114.6 MB 2.3 MB/s eta 0:00:15
   ----------------------------- ---------- 83.4/114.6 MB 2.3 MB/s eta 0:00:14
   ----------------------------- ---------- 84.1/114.6 MB 2.3 MB/s eta 0:00:14
   ----------------------------- ---------- 84.9/114.6 MB 2.3 MB/s eta 0:00:13
   ----------------------------- ---------- 85.7/114.6 MB 2.4 MB/s eta 0:00:13
   ------------------------------ --------- 86.5/114.6 MB 2.4 MB/s eta 0:00:12
   ------------------------------ --------- 87.0/114.6 MB 2.4 MB/s eta 0:00:12
   ------------------------------ --------- 87.0/114.6 MB 2.4 MB/s eta 0:00:12
   ------------------------------ --------- 87.8/114.6 MB 2.4 MB/s eta 0:00:12
   ------------------------------ --------- 88.3/114.6 MB 2.4 MB/s eta 0:00:11
   ------------------------------- -------- 89.1/114.6 MB 2.4 MB/s eta 0:00:11
   ------------------------------- -------- 89.9/114.6 MB 2.5 MB/s eta 0:00:11
   ------------------------------- -------- 90.7/114.6 MB 2.5 MB/s eta 0:00:10
   ------------------------------- -------- 91.5/114.6 MB 2.5 MB/s eta 0:00:10
   -------------------------------- ------- 92.0/114.6 MB 2.5 MB/s eta 0:00:09
   -------------------------------- ------- 92.8/114.6 MB 2.6 MB/s eta 0:00:09
   -------------------------------- ------- 93.6/114.6 MB 2.6 MB/s eta 0:00:09

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.0.0)
Requirement already satisfied: scipy>=1.6.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.15.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting textblob
  Using cached textblob-0.20.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: nltk>=3.9 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from textblob) (3.9.4)
Requirement already satisfied: click in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from nltk>=3.9->textblob) (2026.4.4)
Requirement already satisfied: tqdm in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from nltk>=3.9->textblob) (4.67.3)
Requirement already satisfied: colorama in c:\users\anton\appdata\roaming\python\python312\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Using cached textblob-0.20.0-py3-none-any.whl (624 kB)
Installing collected packages: textblob
Successfully installed textblob-0.20.0

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting vaderSentiment
  Using cached vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests->vaderSentiment) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests->vaderSentiment) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests->vaderSentiment) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests->vaderSentiment) (2026.2.25)
Using cached vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: torch in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (2.11.0)
Requirement already satisfied: filelock in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch) (80.3.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch) (2026.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting transformers
  Using cached transformers-5.6.2-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from transformers) (1.7.2)
Requirement already satisfied: numpy>=1.17 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anton\appdata\roaming\python\python312\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2026.4.4)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.24.1)
Collecting safetensors>=0.4.3 (from transformers)
  Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.27 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.12.1)
Requirement already satisfied: certifi in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: colorama in c:\users\anton\appdata\roaming\python\python312\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\anton\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer->transformers) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Using cached transformers-5.6.2-py3-none-any.whl (10.4 MB)
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Installing collected packages: safetensors, tokenizers, transformers

   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   ------------- -------------------------- 1/3 [tokenizers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]
   -------------------------- ------------- 2/3 [transformers]

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting accelerate
  Using cached accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (2.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anton\appdata\roaming\python\python312\site-packages (from accelerate) (24.2)
Requirement already satisfied: psutil in c:\users\anton\appdata\roaming\python\python312\site-packages (from accelerate) (7.0.0)
Requirement already satisfied: pyyaml in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (2.11.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (1.7.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typer in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: anyio in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.12.1)
Requirement already satisfied: certifi in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools<82 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate) (80.3.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: colorama in c:\users\anton\appdata\roaming\python\python312\site-packages (from tqdm>=4.42.1->huggingface_hub>=0.21.0->accelerate) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: click>=8.2.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface_hub>=0.21.0->accelerate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\anton\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate) (0.1.2)
Using cached accelerate-1.13.0-py3-none-any.whl (383 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.13.0

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.0.0)
Requirement already satisfied: packaging>=20.0 in c:\users\anton\appdata\roaming\python\python312\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: requests in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anton\appdata\local\programs\python\python312\lib\site-packages (from requests) (2026.2.25)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import os
import pandas as pd
import re
import spacy
import sys
import subprocess
import numpy as np
subprocess.check_call([sys.executable, "-m", "spacy", "download", "en_core_web_sm"])

np.random.seed(42)

In [2]:
# 1. Carregar o ficheiro CSV
df_test = pd.read_csv("imdb_reviews_test.csv")

In [3]:
# Estrutura dos dados
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       2000 non-null   str
 1   label      2000 non-null   str
 2   nr_tokens  2000 non-null   int64
dtypes: int64(1), str(2)
memory usage: 47.0 KB

In [4]:
# Número de linhas
print("Total de reviews:", len(df_test))

Total de reviews: 2000

In [5]:
# Distribuição das classes
print(df_test.groupby("label").size())

label
neg     978
pos    1022
dtype: int64

In [6]:
# Estatísticas dos tokens
print(df_test["nr_tokens"].describe())

count    2000.000000
mean      221.584500
std       105.348716
min        14.000000
25%       151.000000
50%       193.500000
75%       284.000000
max       512.000000
Name: nr_tokens, dtype: float64

In [7]:
# Comprimento das reviews
df_test['char_length'] = df_test['text'].str.len()
df_test['word_length'] = df_test['text'].str.split().str.len()

print("Média de caracteres:", df_test['char_length'].mean())
print("Média de palavras:", df_test['word_length'].mean())

Média de caracteres: 970.973
Média de palavras: 175.3285

In [8]:
# Exemplos reais
print(df_test[["text", "label"]].head(3))

                                                text label
0  It's a male bashing bonanza. I saw this on Sci...   neg
1  This film was produced by Producers Releasing ...   neg
2  CHRISTMAS IN AUGUST is a perfect movie. A flaw...   pos

In [9]:
# Exemplos por classe
print(df_test[df_test["label"] == "pos"][["text", "label"]].head(2))
print(df_test[df_test["label"] == "neg"][["text", "label"]].head(2))

                                                 text label
2   CHRISTMAS IN AUGUST is a perfect movie. A flaw...   pos
10  Extremely pinching vision of a war situation w...   pos
                                                text label
0  It's a male bashing bonanza. I saw this on Sci...   neg
1  This film was produced by Producers Releasing ...   neg

In [10]:
print(df_test.head(10))

                                                text label  nr_tokens  \
0  It's a male bashing bonanza. I saw this on Sci...   neg        333
1  This film was produced by Producers Releasing ...   neg        198
2  CHRISTMAS IN AUGUST is a perfect movie. A flaw...   pos        148
3  "Season on the Brink" is one of my favorite bo...   neg        168
4  I initially tuned in to Paranormal State becau...   neg        393
5  Like anyone else who bought this, I was duped ...   neg        502
6  So after the initial disappointment of the fir...   neg        282
7  Donald Pleasance and Peter Cushing united in o...   neg        436
8  A dull stroll through the banalities of Mormon...   neg        117
9  It's too bad these guys, the so called judges,...   neg        152

   char_length  word_length
0         1440          267
1          905          157
2          647          121
3          726          128
4         1778          312
5         2096          391
6         1350          236
7         2184          351
8          532           90
9          644          114

Pré processamento de dados

In [11]:
# 2. Passar o texto para minúsculas

nlp = spacy.load("en_core_web_sm")  

def smart_lower_spacy(text):
    doc = nlp(text)
    result = []
    for token in doc:

        if token.ent_type_:
            result.append(token.text_with_ws)
        else:
            result.append(token.lower_ + token.whitespace_)
    return "".join(result)


df_test["text"] = df_test["text"].apply(smart_lower_spacy)

In [12]:
df_test.head(5)

,text,label,nr_tokens,char_length,word_length
0,it's a male bashing bonanza. i saw this on Sci...,neg,333,1440,267
1,this film was produced by Producers Releasing ...,neg,198,905,157
2,CHRISTMAS in AUGUST is a perfect movie. a flaw...,pos,148,647,121
3,"""Season on the Brink"" is one of my favorite bo...",neg,168,726,128
4,i initially tuned in to Paranormal State becau...,neg,393,1778,312

In [13]:
print(df_test.head(10))

                                                text label  nr_tokens  \
0  it's a male bashing bonanza. i saw this on Sci...   neg        333
1  this film was produced by Producers Releasing ...   neg        198
2  CHRISTMAS in AUGUST is a perfect movie. a flaw...   pos        148
3  "Season on the Brink" is one of my favorite bo...   neg        168
4  i initially tuned in to Paranormal State becau...   neg        393
5  like anyone else who bought this, i was duped ...   neg        502
6  so after the initial disappointment of the fir...   neg        282
7  Donald Pleasance and Peter Cushing united in o...   neg        436
8  a dull stroll through the banalities of Mormon...   neg        117
9  it's too bad these guys, the so called judges,...   neg        152

   char_length  word_length
0         1440          267
1          905          157
2          647          121
3          726          128
4         1778          312
5         2096          391
6         1350          236
7         2184          351
8          532           90
9          644          114

In [14]:
# 3. Remover a pontuação
import string
df_test['text'] = df_test['text'].str.translate(str.maketrans('', '', string.punctuation))

In [15]:
print(df_test.head(10))

                                                text label  nr_tokens  \
0  its a male bashing bonanza i saw this on Sci F...   neg        333
1  this film was produced by Producers Releasing ...   neg        198
2  CHRISTMAS in AUGUST is a perfect movie a flawl...   pos        148
3  Season on the Brink is one of my favorite book...   neg        168
4  i initially tuned in to Paranormal State becau...   neg        393
5  like anyone else who bought this i was duped b...   neg        502
6  so after the initial disappointment of the fir...   neg        282
7  Donald Pleasance and Peter Cushing united in o...   neg        436
8  a dull stroll through the banalities of Mormon...   neg        117
9  its too bad these guys the so called judges ar...   neg        152

   char_length  word_length
0         1440          267
1          905          157
2          647          121
3          726          128
4         1778          312
5         2096          391
6         1350          236
7         2184          351
8          532           90
9          644          114

In [16]:
# 4. Remover stop words
import nltk
nltk.download('stopwords')


from nltk.corpus import stopwords

NEGATION_WORDS = {"no", "not","rather", "couldn't", "wasn't", "didn't", "wouldn't", "shouldn't", "weren't", "don't", "doesn't", "haven't", 
                  "hasn't", "won't", "wont", "hadn't", "never", "none", "nobody", "nothing", "neither", "nor", "nowhere", "isn't", "can't", 
                  "cannot", "mustn't", "mightn't", "shan't", "without", "needn't", "hardly", "less", "little", "rarely", "scarcely", "seldom"
        }

negative_prefixes = ('de', 'dis', 'il', 'im', 'in', 'ir', 'mis', 'non', 'un')
negative_suffixes = ('less',)

stop_words = set(stopwords.words('english'))

df_stopwords = df_test.copy()

# coluna remove todas as stop words, incluindo as negation words
df_stopwords['text'] = df_stopwords['text'].str.split().apply(
    lambda tokens: ' '.join([w for w in tokens if w not in stop_words])
)

# coluna remove stop words, mas mantém as negation words
stops_to_remove = stop_words - NEGATION_WORDS
df_stopwords['text_with_negation_words'] = df_stopwords['text'].str.split().apply(
    lambda tokens: ' '.join([
        w for w in tokens 
        if (w not in stops_to_remove) or w.startswith(negative_prefixes) or w.endswith(negative_suffixes)
    ])
)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lifan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [17]:
print(df_stopwords.head(10))

                                                text label  nr_tokens  \
0  male bashing bonanza saw Sci Fi ago idea seeme...   neg        333
1  film produced Producers Releasing Corp PRC amo...   neg        198
2  CHRISTMAS AUGUST perfect movie flawless movie ...   pos        148
3  Season Brink one favorite books time insightfu...   neg        168
4  initially tuned Paranormal State less find par...   neg        393
5  like anyone else bought duped 20 pieces extrem...   neg        502
6  initial disappointment first Final Fantasy mov...   neg        282
7  Donald Pleasance Peter Cushing united one horr...   neg        436
8  dull stroll banalities Mormon prosthelatizing ...   neg        117
9  bad guys called judges jerks even nominally se...   neg        152

   char_length  word_length                           text_with_negation_words
0         1440          267  male bashing bonanza saw Sci Fi ago idea seeme...
1          905          157  film produced Producers Releasing Corp PRC amo...
2          647          121  CHRISTMAS AUGUST perfect movie flawless movie ...
3          726          128  Season Brink one favorite books time insightfu...
4         1778          312  initially tuned Paranormal State less find par...
5         2096          391  like anyone else bought duped 20 pieces extrem...
6         1350          236  initial disappointment first Final Fantasy mov...
7         2184          351  Donald Pleasance Peter Cushing united one horr...
8          532           90  dull stroll banalities Mormon prosthelatizing ...
9          644          114  bad guys called judges jerks even nominally se...

In [18]:
# Guardar os dados limpos num novo ficheiro CSV
df_stopwords.to_csv('imdb_reviews_test_clean.csv', index=False)

In [19]:
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger_eng')

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lifan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\lifan\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\lifan\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

In [20]:
from nltk.corpus import wordnet

def get_wordnet_pos(word):
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {
        "J": wordnet.ADJ,
        "N": wordnet.NOUN,
        "V": wordnet.VERB,
        "R": wordnet.ADV
    }
    return tag_dict.get(tag, wordnet.NOUN)

def lemmatize_text(text):
    tokens = text.split()
    lemmatized = [
        lemmatizer.lemmatize(word, get_wordnet_pos(word))
        for word in tokens
    ]
    return ' '.join(lemmatized)

In [21]:
df_stopwords['text'] = df_stopwords['text'].apply(lemmatize_text)

df_stopwords['text_with_negation_words'] = df_stopwords['text_with_negation_words'].apply(lemmatize_text)

In [22]:
df_stopwords.head()

,text,label,nr_tokens,char_length,word_length,text_with_negation_words
0,male bashing bonanza saw Sci Fi ago idea seem ...,neg,333,1440,267,male bashing bonanza saw Sci Fi ago idea seem ...
1,film produce Producers Releasing Corp PRC amon...,neg,198,905,157,film produce Producers Releasing Corp PRC amon...
2,CHRISTMAS AUGUST perfect movie flawless movie ...,pos,148,647,121,CHRISTMAS AUGUST perfect movie flawless movie ...
3,Season Brink one favorite book time insightful...,neg,168,726,128,Season Brink one favorite book time insightful...
4,initially tune Paranormal State less find para...,neg,393,1778,312,initially tune Paranormal State less find para...

5. Aplicação de Modelos existentes aos Dados de teste

In [34]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

In [26]:
# Criar coluna numérica da classe real
# Vamos usar a versão pré-processada
df_models = df_stopwords.copy()

# Converter labels em números: neg = 0, pos = 1
df_models["label_num"] = df_models["label"].map({"neg": 0, "pos": 1})

print(df_models[["label", "label_num"]].head())

  label  label_num
0   neg          0
1   neg          0
2   pos          1
3   neg          0
4   neg          0

5.1 Aplicação dos Modelos baseados em Léxicos e regras

In [27]:
# 5.A Previsão usando TextBlob
from textblob import TextBlob

def textblob_predict(text):
    polarity = TextBlob(text).sentiment.polarity
    return 1 if polarity >= 0 else 0

df_models["pred_textblob"] = df_models["text"].apply(textblob_predict)

print(df_models[["text", "label", "pred_textblob"]].head())

                                                text label  pred_textblob
0  male bashing bonanza saw Sci Fi ago idea seem ...   neg              1
1  film produce Producers Releasing Corp PRC amon...   neg              1
2  CHRISTMAS AUGUST perfect movie flawless movie ...   pos              1
3  Season Brink one favorite book time insightful...   neg              0
4  initially tune Paranormal State less find para...   neg              1

In [28]:
# 5.B Previsão usando VADER
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

vader = SentimentIntensityAnalyzer()

def vader_predict(text):
    score = vader.polarity_scores(text)["compound"]
    return 1 if score >= 0 else 0

df_models["pred_vader"] = df_models["text"].apply(vader_predict)

print(df_models[["text", "label", "pred_vader"]].head())

                                                text label  pred_vader
0  male bashing bonanza saw Sci Fi ago idea seem ...   neg           1
1  film produce Producers Releasing Corp PRC amon...   neg           1
2  CHRISTMAS AUGUST perfect movie flawless movie ...   pos           1
3  Season Brink one favorite book time insightful...   neg           1
4  initially tune Paranormal State less find para...   neg           0

In [29]:
import stanza
from stanza.models.common.doc import Document
from tqdm import tqdm

stanza_pipeline = stanza.Pipeline(
    lang="en",
    processors="tokenize,sentiment",
    use_gpu=False
)

def stanza_predict_batch(texts, batch_size=200):
    preds = []

    for i in tqdm(range(0, len(texts), batch_size)):
        batch = texts.iloc[i:i+batch_size].tolist()

        # converter strings em Document objects
        in_docs = [Document([], text=t) for t in batch]

        # processar o lote
        out_docs = stanza_pipeline(in_docs)

        for doc in out_docs:
            sentiments = [sentence.sentiment for sentence in doc.sentences]

            if len(sentiments) == 0:
                preds.append(1)
            else:
                avg_sentiment = sum(sentiments) / len(sentiments)
                # 0=negative, 1=neutral, 2=positive
                preds.append(1 if avg_sentiment >= 1 else 0)

    return preds

df_models["pred_stanza"] = stanza_predict_batch(df_models["text"], batch_size=200)

print(df_models[["text", "label", "pred_stanza"]].head())

2026-04-23 20:08:24 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json: 439kB [00:00, 46.5MB/s]
2026-04-23 20:08:25 INFO: Downloaded file to /home/pmglo/.cache/stanza/1.11.0/resources/resources.json
2026-04-23 20:08:25 WARNING: Language en package default expects mwt, which has been added
2026-04-23 20:08:25 INFO: Loading these models for language: en (English):
==============================
| Processor | Package        |
------------------------------
| tokenize  | combined       |
| mwt       | combined       |
| sentiment | sstplus_charlm |
==============================

2026-04-23 20:08:25 INFO: Using device: cpu
2026-04-23 20:08:25 INFO: Loading: tokenize
2026-04-23 20:08:25 INFO: Loading: mwt
2026-04-23 20:08:25 INFO: Loading: sentiment
2026-04-23 20:08:29 INFO: Done loading processors!
100%|██████████| 10/10 [09:16<00:00, 55.62s/it]

                                                text label  pred_stanza
0  male bashing bonanza saw Sci Fi ago idea seem ...   neg            0
1  film produce Producers Releasing Corp PRC amon...   neg            0
2  CHRISTMAS AUGUST perfect movie flawless movie ...   pos            1
3  Season Brink one favorite book time insightful...   neg            0
4  initially tune Paranormal State less find para...   neg            0

In [30]:
# 5.D Previsão usando SentiWordNet
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("sentiwordnet")
nltk.download("wordnet")
nltk.download("averaged_perceptron_tagger")
nltk.download("averaged_perceptron_tagger_eng")

from nltk.corpus import sentiwordnet as swn
from nltk.tokenize import word_tokenize

def sentiwordnet_predict(text):
    tokens = word_tokenize(text)
    tagged = nltk.pos_tag(tokens)
    
    sentiment_score = 0
    valid_terms = 0
    
    for word, tag in tagged:
        wn_tag = get_wordnet_pos(word)
        
        synsets = wordnet.synsets(word, pos=wn_tag)
        if not synsets:
            continue
        
        synset = synsets[0]
        
        try:
            swn_synset = swn.senti_synset(synset.name())
            sentiment_score += swn_synset.pos_score() - swn_synset.neg_score()
            valid_terms += 1
        except:
            continue
    
    if valid_terms == 0:
        return 1
    
    avg_score = sentiment_score / valid_terms
    return 1 if avg_score >= 0 else 0

df_models["pred_sentiwordnet"] = df_models["text"].apply(sentiwordnet_predict)

print(df_models[["text", "label", "pred_sentiwordnet"]].head())

[nltk_data] Downloading package punkt to /home/pmglo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/pmglo/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package sentiwordnet to
[nltk_data]     /home/pmglo/nltk_data...
[nltk_data]   Package sentiwordnet is already up-to-date!
[nltk_data] Downloading package wordnet to /home/pmglo/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/pmglo/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/pmglo/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

                                                text label  pred_sentiwordnet
0  male bashing bonanza saw Sci Fi ago idea seem ...   neg                  1
1  film produce Producers Releasing Corp PRC amon...   neg                  0
2  CHRISTMAS AUGUST perfect movie flawless movie ...   pos                  1
3  Season Brink one favorite book time insightful...   neg                  0
4  initially tune Paranormal State less find para...   neg                  1

Avaliação dos modelos léxicos

In [31]:
def evaluate_model(y_true, y_pred, model_name, show_report=False):
    return {
        "Model": model_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1-score": f1_score(y_true, y_pred)
    }

In [32]:
# Avaliar cada modelo e armazenar os resultados
results_lexicon = []

results_lexicon.append(evaluate_model(df_models["label_num"], df_models["pred_textblob"], "TextBlob"))
results_lexicon.append(evaluate_model(df_models["label_num"], df_models["pred_vader"], "VADER"))
results_lexicon.append(evaluate_model(df_models["label_num"], df_models["pred_stanza"], "Stanza"))
results_lexicon.append(evaluate_model(df_models["label_num"], df_models["pred_sentiwordnet"], "SentiWordNet"))

results_lexicon_df = pd.DataFrame(results_lexicon)
print(results_lexicon_df)

          Model  Accuracy  Precision    Recall  F1-score
0      TextBlob    0.7115   0.654836  0.920744  0.765352
1         VADER    0.6740   0.630098  0.876712  0.733224
2        Stanza    0.7790   0.864322  0.673190  0.756876
3  SentiWordNet    0.6270   0.597320  0.828767  0.694262

DistilBERT

In [33]:
# Modelo distilbert-base-uncased-finetuned-sst-2-english

from transformers import pipeline

distilbert_pipeline = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

def distilbert_predict(text):
    # cortar texto por segurança
    result = distilbert_pipeline(text[:512])[0]
    return 1 if result["label"] == "POSITIVE" else 0

df_models["pred_distilbert"] = df_models["text"].apply(distilbert_predict)

print(df_models[["text", "label", "pred_distilbert"]].head())

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 2339.29it/s]

                                                text label  pred_distilbert
0  male bashing bonanza saw Sci Fi ago idea seem ...   neg                0
1  film produce Producers Releasing Corp PRC amon...   neg                0
2  CHRISTMAS AUGUST perfect movie flawless movie ...   pos                1
3  Season Brink one favorite book time insightful...   neg                0
4  initially tune Paranormal State less find para...   neg                0

In [34]:
# Avaliação do modelo DistilBERT
result_distilbert = evaluate_model(
    df_models["label_num"],
    df_models["pred_distilbert"],
    "DistilBERT"
)

result_distilbert_df = pd.DataFrame([result_distilbert])
print(result_distilbert_df)

        Model  Accuracy  Precision    Recall  F1-score
0  DistilBERT    0.7725   0.876494  0.645793  0.743662

Comparação final de todos os modelos

In [35]:
results_final = pd.concat(
    [results_lexicon_df, result_distilbert_df],
    ignore_index=True
)

results_final = results_final.sort_values(by="F1-score", ascending=False)

print(results_final)

          Model  Accuracy  Precision    Recall  F1-score
0      TextBlob    0.7115   0.654836  0.920744  0.765352
2        Stanza    0.7790   0.864322  0.673190  0.756876
4    DistilBERT    0.7725   0.876494  0.645793  0.743662
1         VADER    0.6740   0.630098  0.876712  0.733224
3  SentiWordNet    0.6270   0.597320  0.828767  0.694262

Aplicação de 2 Léxico de sentimentos

In [23]:
# 6.
 
# 6.a - Pré-processamento do léxico NRC-lexicon.csv

# Lê o ficheiro mantendo apenas as colunas necessárias
df_lexicon= pd.read_csv("NRC-lexicon.csv", usecols=['English', 'Positive', 'Negative'])

# Remove linhas vazias e garante que as palavras são texto
df_lexicon = df_lexicon.dropna(subset=['English'])

# Converter o lexicon para dicionário 
lex = df_lexicon.set_index('English').to_dict('index')

# Aplicar lowercase às chaves
lex_nrc = {word.lower(): {"positive": int(row["Positive"]), "negative": int(row["Negative"])} 
       for word, row in lex.items()}

print(f"Total de palavras no léxico: {len(lex_nrc)}")
print(f"Visualização das primeiras palavras: {list(lex_nrc.items())[:3]}")

Total de palavras no léxico: 14181
Visualização das primeiras palavras: [('aback', {'positive': 0, 'negative': 0}), ('abacus', {'positive': 0, 'negative': 0}), ('abandon', {'positive': 0, 'negative': 1})]

In [ ]:
import os
import kagglehub
import pandas as pd

# Download do dataset
path = kagglehub.dataset_download("nltkdata/opinion-lexicon")
print("Path to dataset files:", path)

LEXICON_DIR = os.path.join(path, "opinion_lexicon")

pos_file = os.path.join(LEXICON_DIR, "positive-words.txt")
neg_file = os.path.join(LEXICON_DIR, "negative-words.txt")

Downloading to /home/pmglo/_.Projects/Text Mining/trabalho/datasets/nltkdata/opinion-lexicon/1.archive...

100%|██████████| 24.2k/24.2k [00:00<00:00, 1.99MB/s]

Extracting files...
Path to dataset files: /home/pmglo/_.Projects/Text Mining/trabalho/datasets/nltkdata/opinion-lexicon/versions/1

In [8]:
def create_unified_csv(pos_file, neg_file, output_filename):
    data = []

    # Processar palavras Positivas
    with open(pos_file, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            word = line.strip()
            if word and not word.startswith(';'):
                data.append([word.lower(), 1, 0])

    # Processar palavras Negativas
    with open(neg_file, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            word = line.strip()
            if word and not word.startswith(';'):
                data.append([word.lower(), 0, 1])

    # Converter para DataFrame e guardar como CSV
    df_lexicon = pd.DataFrame(data, columns=['English', 'Positive', 'Negative'])

    # Remover possíveis palavras duplicadas
    df_lexicon = df_lexicon.drop_duplicates(subset=['English'])

    df_lexicon.to_csv(output_filename, index=False)
    print(f"Ficheiro '{output_filename}' criado com {len(df_lexicon)} palavras.")
    
    return df_lexicon


df_lexicon = create_unified_csv(pos_file, neg_file, "opinion_lexicon.csv")

Ficheiro 'opinion_lexicon.csv' criado com 6786 palavras.

In [25]:
# 6.b - Pré-processamento do léxico Bing Liu (opinion-lexicon.csv)

# Lê o ficheiro mantendo apenas as colunas necessárias
df_lexicon= pd.read_csv("opinion_lexicon.csv", usecols=['English', 'Positive', 'Negative'])

# Remove linhas vazias e garante que as palavras são texto
df_lexicon = df_lexicon.dropna(subset=['English'])

# Converter o lexicon para dicionário 
lex_opinion = df_lexicon.set_index('English').to_dict('index')

# Aplicar lowercase às chaves
lex_opinion = {word.lower(): {"positive": int(row["Positive"]), "negative": int(row["Negative"])} 
               for word, row in lex_opinion.items()}

print(f"Total de palavras no léxico de opinion: {len(lex_opinion)}")
print(f"Visualização das primeiras palavras: {list(lex_opinion.items())[:3]}")

Total de palavras no léxico de opinion: 6786
Visualização das primeiras palavras: [('a+', {'positive': 1, 'negative': 0}), ('abound', {'positive': 1, 'negative': 0}), ('abounds', {'positive': 1, 'negative': 0})]

In [26]:
# 6.c - Classificador SEM tratamento de negação (baseline)
def classify_lexicon_without_negation(text, lexicon):
    score_pos = 0
    score_neg = 0
    
    if isinstance(text, str):
        words = text.split()
    else:
        words = []
    
    # Agora iteramos sobre a lista de palavras gerada
    for w in words:
        if w in lexicon:
            score_pos += lexicon[w]['positive']
            score_neg += lexicon[w]['negative']
            
    # Determinar a classificação
    if score_pos > score_neg:
        classification = "pos"
    else:
        classification = "neg"
        
    return score_pos, score_neg, classification

In [27]:
# 6.c
# 1 - Applicação de dados de teste com Classificador SEM tratamento de negação baseado no léxico NRC-lexicon.csv
df_test_clean = df_stopwords.copy() # dataset pré-processado sem stop words

df_test_clean[['total_pos_nrc', 'total_neg_nrc', 'classification_nrc']] = df_test_clean['text'].apply(
    lambda x: pd.Series(classify_lexicon_without_negation(x, lex_nrc))
)


df_test_clean.head(10)
#print(df_test_clean.head(10))

,text,label,nr_tokens,char_length,word_length,text_with_negation_words,total_pos_nrc,total_neg_nrc,classification_nrc
0,male bashing bonanza saw Sci Fi ago idea seem ...,neg,333,1440,267,male bashing bonanza saw Sci Fi ago idea seem ...,9,8,pos
1,film produce Producers Releasing Corp PRC amon...,neg,198,905,157,film produce Producers Releasing Corp PRC amon...,12,6,pos
2,CHRISTMAS AUGUST perfect movie flawless movie ...,pos,148,647,121,CHRISTMAS AUGUST perfect movie flawless movie ...,8,10,neg
3,Season Brink one favorite book time insightful...,neg,168,726,128,Season Brink one favorite book time insightful...,7,7,neg
4,initially tune Paranormal State less find para...,neg,393,1778,312,initially tune Paranormal State less find para...,14,23,neg
5,like anyone else bought duped 20 piece extreme...,neg,502,2096,391,like anyone else bought duped 20 piece extreme...,11,23,neg
6,initial disappointment first Final Fantasy mov...,neg,282,1350,236,initial disappointment first Final Fantasy mov...,16,8,pos
7,Donald Pleasance Peter Cushing united one horr...,neg,436,2184,351,Donald Pleasance Peter Cushing united one horr...,25,21,pos
8,dull stroll banality Mormon prosthelatizing ut...,neg,117,532,90,dull stroll banality Mormon prosthelatizing ut...,7,5,pos
9,bad guy call judge jerk even nominally sensiti...,neg,152,644,114,bad guy call judge jerk even nominally sensiti...,7,7,neg

In [28]:
# 6.c
# 2 - Applicação de dados de teste com Classificador SEM tratamento de negação baseado no léxico opinion_lexicon.csv

df_test_clean[['total_pos_opinion', 'total_neg_opinion', 'classification_opinion']] = df_test_clean['text'].apply(
    lambda x: pd.Series(classify_lexicon_without_negation(x, lex_opinion))
)


df_test_clean.head(10)
# print(df_test_clean.head(10))

,text,label,nr_tokens,char_length,word_length,text_with_negation_words,total_pos_nrc,total_neg_nrc,classification_nrc,total_pos_opinion,total_neg_opinion,classification_opinion
0,male bashing bonanza saw Sci Fi ago idea seem ...,neg,333,1440,267,male bashing bonanza saw Sci Fi ago idea seem ...,9,8,pos,9,16,neg
1,film produce Producers Releasing Corp PRC amon...,neg,198,905,157,film produce Producers Releasing Corp PRC amon...,12,6,pos,4,2,pos
2,CHRISTMAS AUGUST perfect movie flawless movie ...,pos,148,647,121,CHRISTMAS AUGUST perfect movie flawless movie ...,8,10,neg,7,7,neg
3,Season Brink one favorite book time insightful...,neg,168,726,128,Season Brink one favorite book time insightful...,7,7,neg,8,5,pos
4,initially tune Paranormal State less find para...,neg,393,1778,312,initially tune Paranormal State less find para...,14,23,neg,13,19,neg
5,like anyone else bought duped 20 piece extreme...,neg,502,2096,391,like anyone else bought duped 20 piece extreme...,11,23,neg,17,12,pos
6,initial disappointment first Final Fantasy mov...,neg,282,1350,236,initial disappointment first Final Fantasy mov...,16,8,pos,17,6,pos
7,Donald Pleasance Peter Cushing united one horr...,neg,436,2184,351,Donald Pleasance Peter Cushing united one horr...,25,21,pos,15,18,neg
8,dull stroll banality Mormon prosthelatizing ut...,neg,117,532,90,dull stroll banality Mormon prosthelatizing ut...,7,5,pos,6,10,neg
9,bad guy call judge jerk even nominally sensiti...,neg,152,644,114,bad guy call judge jerk even nominally sensiti...,7,7,neg,5,7,neg

In [29]:
# 6.d - Classificador COM tratamento de negação 
NEG_WORDS = {
    "no", "not","rather", "couldn't", "wasn't", "didn't", "wouldn't", "shouldn't", "weren't", "don't", "doesn't", "haven't", 
    "hasn't", "won't", "wont", "hadn't", "never", "none", "nobody", "nothing", "neither", "nor", "nowhere", "isn't", "can't", 
    "cannot", "mustn't", "mightn't", "shan't", "without", "needn't", "hardly", "less", "little", "rarely", "scarcely", "seldom"
}

# Definir os prefixos e sufixos como tuplos
neg_prefixes = ('de', 'dis', 'il', 'im', 'in', 'ir', 'mis', 'non', 'un')
neg_suffixes = ('less',)

def classify_lexicon_with_negation(text, lexicon):
    score_pos = 0
    score_neg = 0
    
    if isinstance(text, str):
        words = text.split()
    else:
        words = []
        
    negation_affection = 0 # contador das palavras afetadas pela negação
    
    for w in words:
        
        # 1. Se for palavra de negação explícita, define as próximas 2 palavras como afetadas
        if w in NEG_WORDS:
            negation_affection = 2 
            continue 
            
        # 2. Verificar se a palavra tem os prefixos ou sufixos de negação
        has_negative_affix = w.startswith(neg_prefixes) or w.endswith(neg_suffixes)
        
        # 3. Se a palavra estiver no léxico
        if w in lexicon:
            val_pos = lexicon[w]['positive']
            val_neg = lexicon[w]['negative']
            
            # Se a palavra tem prefixo/sufixo de negação: inverte o sentimento e zera o contador
            if has_negative_affix:
                score_pos += val_neg
                score_neg += val_pos
                negation_affection = 0
                
            # Se não tem prefixo/sufixo, mas está sob o efeito das 3 palavras anteriores
            elif negation_affection > 0:
                score_pos += val_neg
                score_neg += val_pos
              
            
            # Caso normal (sem negação ativa e sem prefixo/sufixo)
            else:
                score_pos += val_pos
                score_neg += val_neg
                
        # 4. Se a palavra tem prefixo/sufixo MAS NÃO está no léxico
        # (Forçamos a classificação como negativa e zeramos o contador)
        elif has_negative_affix:
            score_neg += 1 
            negation_affection = 0

        # Reduz o contador de negação a cada palavra que passa
        if negation_affection > 0:
            negation_affection -= 1
            
    # Determinar a classificação final
    if score_pos > score_neg:
        return score_pos, score_neg, "pos"
    else:
        return score_pos, score_neg, "neg"

In [30]:
# 6.d 
# 1 - Applicação de dados de teste com Classificador COM tratamento de negação baseado no léxico NRC-lexicon.csv
df_test_clean_2 = df_stopwords.copy()

df_test_clean_2[['total_pos_nrc', 'total_neg_nrc', 'classification_nrc']] = df_test_clean_2['text_with_negation_words'].apply(
    lambda x: pd.Series(classify_lexicon_with_negation(x, lex_nrc))
)


df_test_clean_2.head(10)
# print(df_test_clean_2.head(10))

,text,label,nr_tokens,char_length,word_length,text_with_negation_words,total_pos_nrc,total_neg_nrc,classification_nrc
0,male bashing bonanza saw Sci Fi ago idea seem ...,neg,333,1440,267,male bashing bonanza saw Sci Fi ago idea seem ...,9,12,neg
1,film produce Producers Releasing Corp PRC amon...,neg,198,905,157,film produce Producers Releasing Corp PRC amon...,13,7,pos
2,CHRISTMAS AUGUST perfect movie flawless movie ...,pos,148,647,121,CHRISTMAS AUGUST perfect movie flawless movie ...,9,12,neg
3,Season Brink one favorite book time insightful...,neg,168,726,128,Season Brink one favorite book time insightful...,8,7,pos
4,initially tune Paranormal State less find para...,neg,393,1778,312,initially tune Paranormal State less find para...,17,23,neg
5,like anyone else bought duped 20 piece extreme...,neg,502,2096,391,like anyone else bought duped 20 piece extreme...,11,24,neg
6,initial disappointment first Final Fantasy mov...,neg,282,1350,236,initial disappointment first Final Fantasy mov...,15,11,pos
7,Donald Pleasance Peter Cushing united one horr...,neg,436,2184,351,Donald Pleasance Peter Cushing united one horr...,29,23,pos
8,dull stroll banality Mormon prosthelatizing ut...,neg,117,532,90,dull stroll banality Mormon prosthelatizing ut...,7,6,pos
9,bad guy call judge jerk even nominally sensiti...,neg,152,644,114,bad guy call judge jerk even nominally sensiti...,8,6,pos

In [31]:
# 6.d 
# 2 - Applicação de dados de teste com Classificador COM tratamento de negação baseado no léxico opinion_lexicon.csv

df_test_clean_2[['total_pos_opinion', 'total_neg_opinion', 'classification_opinion']] = df_test_clean_2['text_with_negation_words'].apply(
    lambda x: pd.Series(classify_lexicon_with_negation(x, lex_opinion))
)


df_test_clean_2.head(10)
# print(df_test_clean_2.head(10))

,text,label,nr_tokens,char_length,word_length,text_with_negation_words,total_pos_nrc,total_neg_nrc,classification_nrc,total_pos_opinion,total_neg_opinion,classification_opinion
0,male bashing bonanza saw Sci Fi ago idea seem ...,neg,333,1440,267,male bashing bonanza saw Sci Fi ago idea seem ...,9,12,neg,11,17,neg
1,film produce Producers Releasing Corp PRC amon...,neg,198,905,157,film produce Producers Releasing Corp PRC amon...,13,7,pos,4,7,neg
2,CHRISTMAS AUGUST perfect movie flawless movie ...,pos,148,647,121,CHRISTMAS AUGUST perfect movie flawless movie ...,9,12,neg,8,9,neg
3,Season Brink one favorite book time insightful...,neg,168,726,128,Season Brink one favorite book time insightful...,8,7,pos,8,6,pos
4,initially tune Paranormal State less find para...,neg,393,1778,312,initially tune Paranormal State less find para...,17,23,neg,15,25,neg
5,like anyone else bought duped 20 piece extreme...,neg,502,2096,391,like anyone else bought duped 20 piece extreme...,11,24,neg,17,14,pos
6,initial disappointment first Final Fantasy mov...,neg,282,1350,236,initial disappointment first Final Fantasy mov...,15,11,pos,17,9,pos
7,Donald Pleasance Peter Cushing united one horr...,neg,436,2184,351,Donald Pleasance Peter Cushing united one horr...,29,23,pos,18,27,neg
8,dull stroll banality Mormon prosthelatizing ut...,neg,117,532,90,dull stroll banality Mormon prosthelatizing ut...,7,6,pos,6,11,neg
9,bad guy call judge jerk even nominally sensiti...,neg,152,644,114,bad guy call judge jerk even nominally sensiti...,8,6,pos,5,8,neg

Comparação de resultados

In [32]:
def evaluate_classifier(y_true, y_pred, classifier_name):
    return {
        "Classifier": classifier_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, pos_label='pos'),
        "Recall": recall_score(y_true, y_pred, pos_label='pos'),
        "F1-score": f1_score(y_true, y_pred, pos_label='pos')
    }

In [35]:
# Accuracy, Precision, Recall e F1-score dos classificadores com e sem tratamento de negação

results = []

# Lexicon NRC sem tratamento denegação - NRC-Lexicon.csv
results.append(evaluate_classifier(df_test_clean["label"], df_test_clean["classification_nrc"], "NRC-Lexicon (sem negação)"))

# Lexicon opinion sem tratamento denegação - opinion-lexicon.csv
results.append(evaluate_classifier(df_test_clean["label"], df_test_clean["classification_opinion"], "Opinion-Lexicon (sem negação)"))

# Lexicon NRC com tratamento denegação - NRC-Lexicon.csv
results.append(evaluate_classifier(df_test_clean_2["label"], df_test_clean_2["classification_nrc"], "NRC-Lexicon (com negação)"))

# Lexicon opinion com tratamento denegação - opinion-lexicon.csv
results.append(evaluate_classifier(df_test_clean_2["label"], df_test_clean_2["classification_opinion"], "Opinion-Lexicon (com negação)"))


results_lexicons = pd.DataFrame(results)

print(results_lexicons)

                      Classifier  Accuracy  Precision    Recall  F1-score
0      NRC-Lexicon (sem negação)    0.6540   0.623134  0.817025  0.707028
1  Opinion-Lexicon (sem negação)    0.7260   0.734653  0.726027  0.730315
2      NRC-Lexicon (com negação)    0.6470   0.640071  0.706458  0.671628
3  Opinion-Lexicon (com negação)    0.6895   0.731792  0.619374  0.670906

In [36]:
import matplotlib.pyplot as plt
from tqdm import tqdm

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

df_train = pd.read_csv("imdb_reviews_train.csv")
df_train["text"] = df_train["text"].str.lower()
df_train['text'] = df_train['text'].str.translate(str.maketrans('', '', string.punctuation))
df_train['text'] = df_train['text'].str.split().apply(
    lambda tokens: ' '.join([w for w in tokens if w not in stop_words])
)
df_train['text'] = df_train['text'].apply(lemmatize_text)
df_train["label_num"] = df_train["label"].map({"neg": 0, "pos": 1})

y_train = df_train["label_num"]
y_test = df_models["label_num"]

all_results = results_lexicon + [result_distilbert]

tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1, 2), sublinear_tf=True)
X_train_tfidf = tfidf.fit_transform(df_train['text'])
X_test_tfidf = tfidf.transform(df_models['text'])

print(f'Dimensão TF-IDF treino: {X_train_tfidf.shape}')
print(f'Dimensão TF-IDF teste:  {X_test_tfidf.shape}')

Dimensão TF-IDF treino: (41750, 10000)
Dimensão TF-IDF teste:  (2000, 10000)

In [37]:
classifiers = {
    'Logistic Regression': LogisticRegression(max_iter=1000, C=1.0),
    'Naive Bayes': MultinomialNB(alpha=1.0),
    'SVM (LinearSVC)': LinearSVC(max_iter=2000, C=1.0),
    'Random Forest': RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)
}

ml_results = []
for name, clf in classifiers.items():
    print(f'Treinando {name}...')
    clf.fit(X_train_tfidf, y_train)
    y_pred = clf.predict(X_test_tfidf)
    r = evaluate_model(y_test, y_pred, f'ML: {name}')
    all_results.append(r)
    ml_results.append(r)
    print(f'  -> {r}')
    print()

print('=== Resumo Modelos ML Clássicos ===')
print(pd.DataFrame(ml_results).to_string(index=False))

Treinando Logistic Regression...
  -> {'Model': 'ML: Logistic Regression', 'Accuracy': 0.8985, 'Precision': 0.8987341772151899, 'Recall': 0.9031311154598826, 'F1-score': 0.9009272816007808}

Treinando Naive Bayes...
  -> {'Model': 'ML: Naive Bayes', 'Accuracy': 0.8665, 'Precision': 0.8763708873379861, 'Recall': 0.860078277886497, 'F1-score': 0.8681481481481481}

Treinando SVM (LinearSVC)...
  -> {'Model': 'ML: SVM (LinearSVC)', 'Accuracy': 0.889, 'Precision': 0.8952569169960475, 'Recall': 0.8864970645792564, 'F1-score': 0.8908554572271387}

Treinando Random Forest...
  -> {'Model': 'ML: Random Forest', 'Accuracy': 0.854, 'Precision': 0.865, 'Recall': 0.8463796477495108, 'F1-score': 0.8555885262116716}

=== Resumo Modelos ML Clássicos ===
                  Model  Accuracy  Precision   Recall  F1-score
ML: Logistic Regression    0.8985   0.898734 0.903131  0.900927
        ML: Naive Bayes    0.8665   0.876371 0.860078  0.868148
    ML: SVM (LinearSVC)    0.8890   0.895257 0.886497  0.890855
      ML: Random Forest    0.8540   0.865000 0.846380  0.855589

In [ ]:
import torch
import numpy as np
from transformers import (
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding  
)
from torch.utils.data import Dataset as TorchDataset
from sklearn.metrics import accuracy_score, f1_score

# ─ 1. VERIFICAR DISPOSITIVO 
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"A usar: {device.upper()}")

# ─ 2. DATASET COM TOKENIZAÇÃO 
class IMDBDataset(TorchDataset):
    """
    Lazy tokenization: tokeniza apenas quando o item é acedido,
    em vez de tokenizar tudo de uma vez no __init__.
    """
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts.tolist()
        self.labels = labels.tolist()
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __getitem__(self, idx):
        encoding = self.tokenizer(
            self.texts[idx],
            truncation=True,
            max_length=self.max_len
        )
        encoding['labels'] = self.labels[idx]
        return encoding

    def __len__(self):
        return len(self.labels)


# ─ 3. TOKENIZER E MODELO
tokenizer_ft = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')
model_ft = DistilBertForSequenceClassification.from_pretrained(
    'distilbert-base-uncased',
    num_labels=2
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer_ft)

# ─ 4. DATASETS
train_dataset = IMDBDataset(df_train['text'], df_train['label_num'], tokenizer_ft, max_len=128)
test_dataset  = IMDBDataset(df_models['text'], df_models['label_num'], tokenizer_ft, max_len=128)

print(f"Treino: {len(train_dataset)} | Teste: {len(test_dataset)}")


# ─ 5. MÉTRICAS
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    preds = np.argmax(predictions, axis=-1)
    return {
        'accuracy': accuracy_score(labels, preds),
        'f1': f1_score(labels, preds, average='binary')
    }


# ─ 6. TRAINING ARGUMENTS OPTIMIZADOS 
training_args = TrainingArguments(
    output_dir='./ft_results',
    num_train_epochs=2,
    per_device_train_batch_size=32,   
    per_device_eval_batch_size=64,   
    fp16=torch.cuda.is_available(),   
    dataloader_num_workers=4,         
    # Avaliação e logging
    eval_strategy='epoch',
    save_strategy='no',
    logging_steps=50,              
    report_to='none',
    # Optimizador
    learning_rate=2e-5,              
    warmup_ratio=0.1,                
    weight_decay=0.01,

    seed=42,
)

# ─ 7. TRAINER
trainer = Trainer(
    model=model_ft,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
    data_collator=data_collator,      
    processing_class=tokenizer_ft
)

print('A iniciar fine-tuning...')
trainer.train()
print('Fine-tuning concluído.')

A usar: CPU
⚠️  AVISO: Treino em CPU será muito lento.
   → Considera usar Google Colab (GPU gratuita) ou Kaggle Notebooks.

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 657.05it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Treino: 41750 | Teste: 2000
A iniciar fine-tuning...

/home/pmglo/_.Projects/Text Mining/trabalho/.venv/lib/python3.12/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [ ]:
preds_ft = trainer.predict(test_dataset)
y_pred_ft = np.argmax(preds_ft.predictions, axis=1)

r = evaluate_model(y_test, y_pred_ft, 'ML: DistilBERT Fine-tuned')
all_results.append(r)
print(r)

In [ ]:
import requests
import json
import time

# ============================================================
# CONFIGURAÇÃO DA API — iaedu.pt
# ============================================================
API_URL    = os.getenv('IAEDU_API_URL', '')
API_KEY    = os.getenv('IAEDU_API_KEY', '')
CHANNEL_ID = os.getenv('IAEDU_CHANNEL_ID', '')
THREAD_ID  = os.getenv('IAEDU_THREAD_ID', '')

# Formato SSE próprio da iaedu:
# {"run_id": "...", "type": "start"|"token"|"done"|"error", "content": "..."}

def llm_call_raw(message_text, delay_after=2.0):
    """Fazer uma chamada à API e devolver o texto completo da resposta."""
    form_data = {
        'channel_id': (None, CHANNEL_ID),
        'thread_id':  (None, THREAD_ID),
        'user_info':  (None, '{}'),
        'message':    (None, message_text),
    }
    resp = requests.post(
        API_URL,
        headers={'x-api-key': API_KEY},
        files=form_data,
        stream=True,
        timeout=60
    )
    resp.raise_for_status()

    full_text = ''
    error_msg = None
    for raw_line in resp.iter_lines():
        if not raw_line:
            continue
        line = raw_line.decode('utf-8') if isinstance(raw_line, bytes) else raw_line
        try:
            chunk = json.loads(line)
            ctype   = chunk.get('type', '')
            content = chunk.get('content', '')
            if ctype == 'token':
                full_text += content
            elif ctype == 'done' and not full_text:
                # Alguns agentes enviam a resposta completa no 'done'
                full_text = content
            elif ctype == 'error':
                error_msg = content
        except (json.JSONDecodeError, KeyError):
            pass

    time.sleep(delay_after)   # respeitar rate limit

    if error_msg:
        raise RuntimeError(f'API error: {error_msg}')
    return full_text.strip()


def llm_predict(text, system_prompt, max_retries=4, base_delay=3.0):
    """Classificar sentimento via iaedu.pt.
    
    O system_prompt e a instrução de classificação são incluídos na mensagem.
    Retorna 1 (pos), 0 (neg) ou -1 (erro / resposta ambígua).
    """
    full_message = (
        f"{system_prompt}\n\n"
        f"Classify the sentiment of this movie review as positive or negative. "
        f'Reply ONLY with "pos" or "neg". No other text.\n\nReview: {text[:1000]}'
    )

    for attempt in range(max_retries):
        try:
            answer = llm_call_raw(full_message, delay_after=base_delay + attempt * 2)
            answer_lower = answer.lower()
            if 'pos' in answer_lower:
                return 1
            elif 'neg' in answer_lower:
                return 0
            else:
                return -1   # resposta ambígua
        except RuntimeError as e:
            # Rate limit ou erro da API — esperar mais
            wait = base_delay * (2 ** attempt)
            print(f'  [tentativa {attempt+1}] {e} — aguardar {wait:.0f}s')
            time.sleep(wait)
        except Exception as e:
            if attempt < max_retries - 1:
                time.sleep(base_delay)
            else:
                print(f'  [erro após {max_retries} tentativas]: {e}')
                return -1
    return -1

# ============================================================
# Definição dos 3 prompts
# ============================================================
PROMPT_GENERIC = 'You are a sentiment analysis assistant. Classify text as positive or negative.'

PROMPT_DOMAIN = """You are a sentiment analysis assistant specialized in movie reviews from IMDB.
Reviews can be positive (the reviewer liked the movie) or negative (the reviewer disliked the movie).
Consider the overall tone, specific praise or criticism, and the reviewer's recommendation."""

PROMPT_FEWSHOT = """You are a sentiment analysis assistant for IMDB movie reviews.

Here are some examples:
- "This movie was amazing, great acting and beautiful cinematography!" -> pos
- "Terrible film, waste of time, the plot made no sense at all." -> neg
- "A masterpiece of cinema, one of the best films I've ever seen." -> pos
- "Worst movie I have ever seen, absolutely horrible acting and script." -> neg
- "Loved every minute, the director did an outstanding job." -> pos
- "Boring and predictable, I fell asleep halfway through." -> neg"""

print('API iaedu.pt configurada.')

# Teste rápido de ligação
test_result = llm_predict("This movie was absolutely fantastic!", PROMPT_GENERIC)
print(f'Teste: {"OK → pos" if test_result == 1 else "OK → neg" if test_result == 0 else "ERRO (-1)"}')

In [ ]:
SAMPLE_SIZE = 200
df_sample = df_models.sample(n=SAMPLE_SIZE, random_state=42).copy()

prompts = [
    ('LLM: Genérico', PROMPT_GENERIC),
    ('LLM: Domínio', PROMPT_DOMAIN),
    ('LLM: Few-shot', PROMPT_FEWSHOT)
]

for prompt_name, prompt in prompts:
    preds = []
    for text in tqdm(df_sample['text'], desc=prompt_name):
        preds.append(llm_predict(text, prompt))
        time.sleep(0.5)

    col = f'pred_{prompt_name}'
    df_sample[col] = preds

    valid_mask = df_sample[col] >= 0
    valid = df_sample[valid_mask]
    n_errors = (~valid_mask).sum()

    print(f'\n{prompt_name}: {len(valid)} válidas, {n_errors} erros')
    if len(valid) > 0:
        r = evaluate_model(valid['label_num'], valid[col], prompt_name, show_report=True)
        all_results.append(r)
        print(r)
    print()

In [ ]:
results_df = pd.DataFrame(all_results).sort_values('F1-score', ascending=False).reset_index(drop=True)

In [ ]:
fig, ax = plt.subplots(figsize=(14, max(6, len(results_df) * 0.5)))

metrics_cols = ['Accuracy', 'Precision', 'Recall', 'F1-score']
x = np.arange(len(results_df))
width = 0.2

for i, metric in enumerate(metrics_cols):
    bars = ax.barh(x + i * width, results_df[metric], width, label=metric, alpha=0.85)

ax.set_yticks(x + width * 1.5)
ax.set_yticklabels(results_df['Model'])
ax.set_xlim(0, 1.05)
ax.set_xlabel('Score')
ax.set_title('Comparação de Modelos — Análise de Sentimento IMDB Reviews')
ax.legend(loc='lower right')
ax.invert_yaxis()
plt.tight_layout()
plt.show()

In [ ]:
best = results_df.iloc[0]
print(f"\nMelhor modelo: {best['Model']}")
print(f"  Accuracy:  {best['Accuracy']}")
print(f"  Precision: {best['Precision']}")
print(f"  Recall:    {best['Recall']}")
print(f"  F1-score:  {best['F1-score']}")